apiVersion: v1
kind: Secret
metadata:
  name: hl-project-secrets
  namespace: hl-project
type: Opaque
data:
  DB_USER: c2ltaWxhcl91c2Vy
  DB_PASS: c2ltaWxhcl9wYXNz
  DB_NAME: c2ltaWxhcl9tb3ZpZXM=
  DJANGO_SECRET_KEY: cHJvZHVjdGlvbi1zZWNyZXQta2V5
  RABBITMQ_USER: c3R1ZGVudA==
  RABBITMQ_PASSWORD: cXdlcnR5
