server {
    listen 80;
    server_name localhost;

    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # На любой другой запрос возвращаем 404 (этот сервер только для статики)
    location / {
        return 404;
    }
}
