apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: hl-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: mher/flower:2.0
          command: ["celery", "flower", "--port=5555"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5555
          env:
            - name: CELERY_BROKER_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)//"
          envFrom:
            - configMapRef:
                name: hl-project-config
            - secretRef:
                name: hl-project-secrets
